volumes:
    db:
    backups:
networks:
    net:
        attachable: false
services:
    db:
        image: docker.io/postgres:14
        ports:
            - "5432:5432"       
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "5"
        volumes:
            - db:/var/lib/postgresql/data/
        networks:
            - net
        env_file:
            - ./backend/.env_prod
        restart: on-failure
    app:
        depends_on:
            - db
        image: expanse-oauth-fix-v1:1.0
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "5"
        working_dir: /app/
        volumes:
            - backups:/app/backend/backups/
        networks:
            - net
        ports:
            - "1301:1301"
        environment:
            - VERSION=3.0.0
        env_file:
            - ./backend/.env_prod
        entrypoint: []
        command: sh -c "wait-for-it db:5432 -t 0 && cd ./backend/ && npm run prod"
        restart: on-failure
