volumes:
    db:
    backups:
networks:
    net:
        attachable: false
services:
    db:
        image: docker.io/postgres:14
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "5"
        volumes:
            - db:/var/lib/postgresql/data/
        networks:
            - net
        env_file:
            - ./backend/.env_prod
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 10s
        restart: unless-stopped
    app:
        depends_on:
            db:
                condition: service_healthy
        build:
            context: .
        image: expanse-oauth-fix-v1:1.0
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "5"
        working_dir: /app/
        volumes:
            - backups:/app/backend/backups/
        networks:
            - net
        ports:
            - "1301:1301"
        environment:
            - VERSION=3.0.0
        env_file:
            - ./backend/.env_prod
        entrypoint: []
        command: sh -c "wait-for-it db:5432 -t 0 && cd ./backend/ && npm run prod"
        restart: unless-stopped
